on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag from CPython repository'
        required: true
        default: 'v3.13.7'
jobs:
  inform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - uses: actions/checkout@master
        with:
          repository: python/cpython
          ref: ${{ github.event.inputs.tag }}
      - run: make venv
        working-directory: ./Doc
      - run: |
          echo "" >> conf.py
          echo "notfound_context = {" >> conf.py
          echo "    'title': 'Generating file'," >> conf.py
          echo "    'body': '<h1>Generating file</h1>File is being <a href=\"https://github.com/m-aciek/python-docs-pdf/actions/runs/${{ github.run_id }}\">generated</a>. It should be available soon.'" >> conf.py
          echo "}" >> conf.py
        working-directory: ./Doc
      - run: make html
        working-directory: ./Doc
      - run: |
          sed -i 's|/en/latest/|https://docs.python.org/3/|g' ./build/html/404.html
        working-directory: ./Doc
      - uses: actions/upload-artifact@master
        with:
          path: ./Doc/build/html/404.html
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - uses: actions/checkout@master
        with:
          repository: python/cpython
          ref: ${{ github.event.inputs.tag }}
      - run: make venv
        working-directory: ./Doc
      - run: sudo apt-get update
      - run: sudo apt-get install -y latexmk texlive-xetex fonts-freefont-otf xindy
      - run: make dist-pdf
        working-directory: ./Doc
      - uses: actions/upload-artifact@master
        with:
          name: python-${{ github.event.inputs.tag }}-docs-pdf-a4.zip
          path: ./Doc/dist/python-${{ github.event.inputs.tag }}-docs-pdf-a4.zip
      - uses: actions/upload-artifact@master
        with:
          name: python-${{ github.event.inputs.tag }}-docs-pdf-a4.tar.bz2
          path: ./Doc/dist/python-${{ github.event.inputs.tag }}-docs-pdf-a4.tar.bz2
