on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag from CPython repository'
        required: true
        default: 'v3.13.7'
permissions:
  contents: write
jobs:
  inform:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure input tag is latest patch for its major.minor
        run: |
          input_tag="${{ github.event.inputs.tag }}"
          major_minor=$(echo "$input_tag" | grep -oE '^v[0-9]+\.[0-9]+')
          latest_patch=$(git ls-remote --tags https://github.com/python/cpython.git | \
            awk '{print $2}' | grep -E "refs/tags/${major_minor}\\.([0-9]+([abrc][0-9]+)?)$" | \
            sed 's|refs/tags/||' | sort -V | tail -n1)
          if [ "$input_tag" != "$latest_patch" ]; then
            echo "Provided tag $input_tag is not the latest patch for $major_minor (latest: $latest_patch)." >&2
            exit 1
          fi
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - uses: actions/checkout@master
        with:
          repository: python/cpython
          ref: ${{ github.event.inputs.tag }}
      - run: make venv
        working-directory: ./Doc
      - run: |
          echo "" >> conf.py
          echo "notfound_context = {" >> conf.py
          echo "    'title': 'Generating file'," >> conf.py
          echo "    'body': '<h1>Generating file</h1>File is being <a href=\"https://github.com/m-aciek/python-docs-pdf/actions/runs/${{ github.run_id }}\">generated</a>. It should be available soon.'" >> conf.py
          echo "}" >> conf.py
        working-directory: ./Doc
      - run: make html
        working-directory: ./Doc
      - run: |
          sed -i 's|/en/latest/|https://docs.python.org/3/|g' ./build/html/404.html
        working-directory: ./Doc
      - uses: actions/upload-artifact@master
        with:
          path: ./Doc/build/html/404.html
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Set major_minor variable
        id: majorminor
        run: |
          input_tag="${{ github.event.inputs.tag }}"
          major_minor=$(echo "$input_tag" | grep -oE '^[vV]([0-9]+\.[0-9]+)')
          major_minor=${major_minor#v}
          echo "major_minor=$major_minor" >> $GITHUB_OUTPUT
      - name: Check and copy 404.html as zip/tar.bz2 if not exist
        run: |
          set -e
          mkdir -p gh-pages/3
          for ext in zip tar.bz2; do
            target="gh-pages/3/python-${{ steps.majorminor.outputs.major_minor }}-docs-pdf-a4.$ext"
            if [ ! -f "$target" ]; then
              cp ./Doc/build/html/404.html "$target"
            fi
          done
      - name: Commit 404.html placeholders
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add 3/python-${{ steps.majorminor.outputs.major_minor }}-docs-pdf-a4.zip 3/python-${{ steps.majorminor.outputs.major_minor }}-docs-pdf-a4.tar.bz2 || true
          git commit -m "Add 404.html placeholders for missing PDF archives for ${{ steps.majorminor.outputs.major_minor }}" || true
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: gh-pages
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure input tag is latest patch for its major.minor
        run: |
          input_tag="${{ github.event.inputs.tag }}"
          major_minor=$(echo "$input_tag" | grep -oE '^v[0-9]+\.[0-9]+')
          latest_patch=$(git ls-remote --tags https://github.com/python/cpython.git | \
            awk '{print $2}' | grep -E "refs/tags/${major_minor}\\.([0-9]+([abrc][0-9]+)?)$" | \
            sed 's|refs/tags/||' | sort -V | tail -n1)
          if [ "$input_tag" != "$latest_patch" ]; then
            echo "Provided tag $input_tag is not the latest patch for $major_minor (latest: $latest_patch)." >&2
            exit 1
          fi
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - uses: actions/checkout@master
        with:
          repository: python/cpython
          ref: ${{ github.event.inputs.tag }}
      - run: make venv
        working-directory: ./Doc
      - run: sudo apt-get update
      - run: sudo apt-get install -y latexmk texlive-xetex fonts-freefont-otf xindy
      - run: make dist-pdf
        working-directory: ./Doc
      - name: Strip leading v from tag
        id: tag-no-v
        run: |
          echo "tag_no_v=${GITHUB_EVENT_INPUTS_TAG#v}" >> $GITHUB_OUTPUT
        env:
          GITHUB_EVENT_INPUTS_TAG: ${{ github.event.inputs.tag }}
      - uses: actions/upload-artifact@master
        with:
          name: python-${{ steps.tag-no-v.outputs.tag_no_v }}-docs-pdf-a4.zip
          path: ./Doc/dist/${{ github.event.inputs.tag }}-docs-pdf-a4.zip
      - uses: actions/upload-artifact@master
        with:
          name: python-${{ steps.tag-no-v.outputs.tag_no_v }}-docs-pdf-a4.tar.bz2
          path: ./Doc/dist/${{ github.event.inputs.tag }}-docs-pdf-a4.tar.bz2
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Set major_minor variable
        id: majorminor
        run: |
          input_tag="${{ github.event.inputs.tag }}"
          major_minor=$(echo "$input_tag" | grep -oE '^[vV]([0-9]+\.[0-9]+)')
          major_minor=${major_minor#v}
          echo "major_minor=$major_minor" >> $GITHUB_OUTPUT
      - name: Copy generated archives to gh-pages
        run: |
          mkdir -p gh-pages/3
          cp ./Doc/dist/${{ github.event.inputs.tag }}-docs-pdf-a4.zip gh-pages/3/python-${{ steps.majorminor.outputs.major_minor }}-docs-pdf-a4.zip
          cp ./Doc/dist/${{ github.event.inputs.tag }}-docs-pdf-a4.tar.bz2 gh-pages/3/python-${{ steps.majorminor.outputs.major_minor }}-docs-pdf-a4.tar.bz2
      - name: Commit generated archives
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add 3/python-${{ steps.majorminor.outputs.major_minor }}-docs-pdf-a4.zip 3/python-${{ steps.majorminor.outputs.major_minor }}-docs-pdf-a4.tar.bz2
          git commit -m "Update PDF archives for ${{ steps.majorminor.outputs.major_minor }}"
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: gh-pages
